version: '2'

services:
  nginx:
    container_name: proxy
    restart: always
    build: 
      context: ./nginx/
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/log/nginx:/var/log/nginx
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    volumes_from:
      - web
    links:
     - web:web
  mysql:
        container_name: mysql
        image: mysql:8.0
        restart: always
        ports:
          - "3306:3306"
        env_file: .env
        volumes:
          - ./WebApp/scripts/:/scripts
  web:
    container_name: web
    restart: always
    env_file: .env
    image: web
    build: ./
    command: >
        bash -c "python wait_for_mysql.py &&
        ./manage.py migrate &&
        ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
