version: '2'

services:
  # postgres:
  #   image: postgres:11.6
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file: .env

  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    image: web
    build: ./
    command: >
        bash -c "python wait_for_mysql.py &&
        ./manage.py migrate &&
        ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
