version: '2'

services:
  # postgres:
  #   image: postgres:11.6
  mysql:
    container_name: db_server
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./WebApp/scripts/import_mysql_backup.sh:/scripts/import_mysql_backup.sh
      - ./WebApp/scripts/tpc_tax_calculator.sql:/scripts/tpc_tax_calculator.sql
      - ./WebApp/scripts/:/scripts


  web:
    container_name: web_server
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - MYSQL_DATABASE=mysql_data
    image: web
    build: ./
    command: >
        bash -c "python wait_for_mysql.py &&
        ./manage.py migrate &&
        ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql


  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
