site_name: django-rest-template
site_description: Template for Django API applications
repo_url: https://github.com/Urban Institute/django-rest-template
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/Urban Institute">Urban Institute</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
