# Generated by Django 3.1.4 on 2021-02-09 17:20

from django.db import models, migrations
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group, Permission
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)

def add_group_permissions(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None

    run_add_perm = Permission.objects.get(name='Can add run')
    run_view_perm = Permission.objects.get(name='Can view run')
    result_view_perm = Permission.objects.get(name='Can view results')
    budget_view_perm = Permission.objects.get(name='Can view budget')
    budget_change_perm = Permission.objects.get(name='Can change budget')

    #Admin
    group, created = Group.objects.get_or_create(name='Administrators')
    if created:
        group.permissions.add(run_add_perm, run_view_perm)
        group.permissions.add(budget_view_perm)
        group.permissions.add(result_view_perm)
        logger.info('Administrators Group created')

    #Researcher
    group, created = Group.objects.get_or_create(name='Researchers')
    if created:
        group.permissions.add(run_add_perm, run_view_perm)
        group.permissions.add(budget_view_perm)
        group.permissions.add(result_view_perm)
        logger.info('Researchers User Group created')

    #DataSteward
    group, created = Group.objects.get_or_create(name='DataStewards')
    if created:
        group.permissions.add(budget_change_perm, budget_view_perm)
        group.permissions.add(run_view_perm)
        group.permissions.add(result_view_perm)
        logger.info('DataStewards User Group created')

class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20210113_1653'),
        ('users', '0003_auto_20210111_2209'),
    ]

    operations = [
        migrations.RunPython(add_group_permissions),
    ]

