# Generated by Django 3.1.4 on 2021-01-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Run',
        ),
    ]
