# Generated by Django 3.1.4 on 2021-01-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
