# Generated by Django 3.1.4 on 2021-01-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0005_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='budget_allocated',
            new_name='total_budget_allocated',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='budget_used',
            new_name='total_budget_used',
        ),
        migrations.AlterField(
            model_name='budget',
            name='researcher_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.JSONField()),
                ('return_to_researcher', models.BooleanField(default=False)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('researcher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.run')),
            ],
        ),
    ]
