# Generated by Django 3.1.4 on 2021-02-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20210113_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_budget_allocated',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
