# Generated by Django 3.1.4 on 2021-03-05 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210223_2017'),
        ('v1', '0007_auto_20210209_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateBudget',
            fields=[
                ('researcher_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('total_budget_allocated', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('total_budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
