# Generated by Django 3.1.4 on 2021-07-08 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0008_intermediatebudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('command_type', models.IntegerField(choices=[(1, 'OLS'), (2, 'Tabulation')])),
                ('sanitized_command_input', models.JSONField()),
                ('researcher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfidentialDataResult',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.JSONField()),
                ('display_results_decision', models.BooleanField(default=False)),
                ('release_results_decision', models.BooleanField(default=False)),
                ('privacy_budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.command')),
            ],
        ),
        migrations.CreateModel(
            name='ConfidentialDataRun',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('epsilon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_time_run_submitted', models.DateTimeField(auto_now_add=True)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.command')),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticDataResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('privacy_budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.command')),
            ],
        ),
        migrations.CreateModel(
            name='SyntheticDataRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epsilon', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_time_run_submitted', models.DateTimeField(auto_now_add=True)),
                ('command_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.command')),
            ],
        ),
        migrations.RenameModel(
            old_name='Budget',
            new_name='PublicUseBudget',
        ),
        migrations.RenameModel(
            old_name='IntermediateBudget',
            new_name='ReviewAndRefinementBudget',
        ),
        migrations.RemoveField(
            model_name='run',
            name='researcher_id',
        ),
        migrations.RenameField(
            model_name='publicusebudget',
            old_name='total_budget_used',
            new_name='total_budget_available',
        ),
        migrations.RenameField(
            model_name='reviewandrefinementbudget',
            old_name='total_budget_used',
            new_name='total_budget_available',
        ),
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
