# Generated by Django 3.1.4 on 2021-07-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_auto_20210708_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicusebudget',
            old_name='total_budget_available',
            new_name='total_budget_used',
        ),
        migrations.RenameField(
            model_name='reviewandrefinementbudget',
            old_name='total_budget_available',
            new_name='total_budget_used',
        ),
    ]
