# Generated by Django 3.1.4 on 2021-07-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_auto_20210708_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticdataresult',
            name='run_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='syntheticdatarun',
            name='run_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
