# Generated by Django 3.1.4 on 2021-07-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_auto_20210708_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentialdataresult',
            name='run_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='v1.confidentialdatarun'),
        ),
        migrations.AlterField(
            model_name='syntheticdataresult',
            name='run_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='v1.syntheticdatarun'),
        ),
    ]
