# Generated by Django 3.1.4 on 2021-07-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_auto_20210722_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='command_title',
            field=models.CharField(default='Command_{command_id}', max_length=100),
        ),
    ]
