# Generated by Django 3.1.4 on 2021-07-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_auto_20210727_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='command_title',
            new_name='command_name',
        ),
    ]
