# Generated by Django 3.1.4 on 2021-07-28 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0017_auto_20210728_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='command',
            unique_together={('command_name', 'researcher_id')},
        ),
    ]
