# Generated by Django 3.1.4 on 2021-08-18 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1', '0019_auto_20210818_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='confidentialdataresult',
            name='researcher_id',
            field=models.ForeignKey(db_column='researcher_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confidentialdatarun',
            name='researcher_id',
            field=models.ForeignKey(db_column='researcher_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syntheticdataresult',
            name='researcher_id',
            field=models.ForeignKey(db_column='researcher_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syntheticdatarun',
            name='command_id',
            field=models.ForeignKey(db_column='command_id', on_delete=django.db.models.deletion.CASCADE, to='v1.command'),
        ),
    ]
